version: 2
jobs:
  build:
    macos:
      xcode: "11.1.0"
    steps:
      - checkout
      - run:
          name: Swift build
          command: swift build
      - run:
          name: Generate Xcode Project
          command: swift package generate-xcodeproj
      - run:
          name: Test
          command: xcodebuild -scheme CurlDSL-Package -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' -enableCodeCoverage YES build test
