name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: Swift build
        run: swift build
      - name: Generate Xcode Project
        run: swift package generate-xcodeproj
      - name: Swift test
        run: xcodebuild -scheme CurlDSL-Package -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' -enableCodeCoverage YES build test
