name: Jazzy Docs
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Jazzy
        run: gem install jazzy
      - name: Run Jazzy
        run: jazzy
      - name: Deploy
        uses: maxheld83/ghpages@master
        secrets: ${{ secrets.ACCESS_TOKEN }}
        env:
          BUILD_DIR: docs
